accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('doctors/',views.doctors_list ,name='doctors-list'),
    path('login/',views.user_login ,name='login'),
    path('signup/',views.signup ,name='signup'),
    path('myprofile/',views.myprofile ,name='myprofile'),
    path('user/update',views.user_update ,name='user-update'),
    path('myprofile/update/',views.update_profile ,name='profile-update'),
    path('doctors/<str:slug>/',views.doctor_detail ,name='doctor-detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace= 'accounts')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy  as _
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.text import slugify



GENDER= (
    ('male', 'ذكر'),
    ('female', 'انثى'),
)
specialist = (
    ('جلدية', 'جلدية'),
    ('اسنان', 'اسنان'),
    ('اطفال حديثي الولاد', 'اطفال حديثي الولاد'),
    ('مخ واعصاب', 'مخ واعصاب'),
    ('عظام', 'عظام'),
    ('نساء', 'نساء'),
    ('انف واذن وحنجرة', 'انف واذن وحنجرة'),
    ('قلب واوعية دموية', 'قلب واوعية دموية'),
    ('امراض دم', 'امراض دم'),
    ('جراحه', 'جراحه'),
    ('تجميل', 'تجميل'),
    
)
class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    name =models.CharField(_('الاسم '),max_length=40)
    who_iam = models.TextField(_("من انا "),max_length=250)
    specialist = models.CharField(_("التخصص"),choices=specialist ,max_length=50,default='جلدية')
    subtitle = models.CharField(_("نبذة عنك"), max_length=150)
    number_phone = models.CharField(_(" رقم الهاتف"), max_length=150)
    address = models.CharField(_("العنوان بالتفصيل"), max_length=150)
    price = models.IntegerField(_("سعر الكشف "),blank = True,default=1)       
    working_hours = models.IntegerField(_("عدد ساعات العمل"),blank = True,default=1)
    facebook  = models.CharField(max_length = 150,blank = True)
    google  = models.CharField(max_length = 150,blank = True)
    twitter  = models.CharField(max_length = 150,blank = True)
    waiting_time = models.IntegerField(_("مدة الانتظار"),blank = True,default=1)
    image = models.ImageField(_("الصورة الشخصية"), upload_to= "profile",blank=True )
    gender = models.CharField(_("الجنس"), max_length=10,choices=GENDER,default='male')
    slug = models.SlugField(max_length=200 ,unique=True,blank=True,null=True)
    created_at = models.DateTimeField(_("وقت الانضمام"),auto_now_add=True)
    is_doctor = models.BooleanField(default=True)
    class Meta:
        # تحديد اسم الكلاس في admin panel 
        verbose_name = _("الملف الشخصي")
        verbose_name_plural = _("ملفات شخصية")
    def __str__(self):
        return self.name
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username,allow_unicode=True)
        super(Profile, self).save(*args, **kwargs)

@receiver(post_save, sender=User)
def save_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance, name=instance.username)
         

# class ProfilePatient(models.Model):
#     user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
#     name =models.CharField(_('الاسم '),max_length=40)
#     gender = models.CharField(_("الجنس"), max_length=10,choices=GENDER,default='male')


#     class Meta:
#         # تحديد اسم الكلاس في admin panel 
#         verbose_name = _("الملف الشخصي")
#         verbose_name_plural = _(" المرضى  ")

#     def __str__(self):
#         return self.name
     

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, ProfilePatient



class UserCreateForm(UserCreationForm):
    username = forms.CharField(label='اسم المستخدم')    
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الثاني')
    email = forms.EmailField(label='البريد الالكتروني')
    password1 = forms.CharField(label='كلمة المرور', widget=forms.PasswordInput,min_length=8)
    password2 = forms.CharField(label='تاكيد كلمة المرور', widget=forms.PasswordInput,min_length=8)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name','email','password1','password2')

class LoginForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم')
    password = forms.CharField(label='كلمة المرور', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']



class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الثاني')
    email = forms.CharField(label='البريد الالكتروني')
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', ]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'who_iam','specialist','subtitle','number_phone','address','price','working_hours','facebook','google','twitter','waiting_time','image','gender']




# class PatientUpdateForm(forms.ModelForm):
#     class Meta:
#         model = ProfilePatient
#         fields = '__all__'

accounts/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import Profile , ProfilePatient
from .forms import LoginForm ,UserUpdateForm , UserCreateForm ,ProfileUpdateForm ,PatientUpdateForm
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
 
# Create your views here.
def doctors_list(request):
    doctors = Profile.objects.all()  
    context ={
        'doctors':doctors
    }
    return render(request,'user/doctors_list.html',context=context)


def doctor_detail(request,slug):
    doctor_detail = Profile.objects.get(slug=slug)
    context ={
        'doctor_detail':doctor_detail
    }
    return render(request,'user/doctor_details.html',context=context)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username= request.POST['username']
        password= request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:doctors-list')
    else:
        form = LoginForm()
    return render(request,'user/login.html',{'form':form})
 


#@login_required(login_url="accounts:login")#  I can do it without (login_url="accounts:login") i can define LOGIN_URL in Settings
@login_required()
def myprofile(request):
    
    profile = Profile.objects.get(user=request.user)
    
    return render(request,'user/myprofile.html',{'profile':profile})  
 

@login_required()
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
             
            return redirect('accounts:myprofile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        
    return render(request,'user/update_user.html',{'user_form':user_form})

def signup(request):
    if request.method =='POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print(request.user)
            return redirect('accounts:doctors-list')
    else:
        form = UserCreateForm()
    
    return render(request,'user/signup.html',{'form':form})
@login_required()
def update_profile(request):
    user_form = UserUpdateForm(instance=request.user)
    profile_form = ProfileUpdateForm(instance=request.user.profile)
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:myprofile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm( instance=request.user.profile)

    return render(request,'user/update_profile.html',{'profile_form':profile_form ,'user_form':user_form})
 
 

accounts/templates/user/doctor_details.html
{% extends "base.html" %}

{% load static %}



{% block body %}

{% include "user/search.html" %}


<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div >
                                {% if doctor_detail.image %}
                                <img class="img-circle" src="{{doctor_detail.image.url}}" alt="" width="100" height="100">

                                {% else %}
                                <img class="img-circle" src="{% static 'img/profile.jpg' %}" alt="" width="100" height="100">

                                {% endif %}
                                
                                   
                            </div>
                            <div class="jobs_conetent">
                                <a href="#" ><h4>{{doctor_detail.name}}</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> مصر  ,{{doctor_detail.address}} </p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i>   {{doctor_detail.waiting_time}} وقت الانتظار  دقيقه</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="boxed-btn3" href="">حجز كشف</a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="descript_wrap white-bg">
                    <div class="single_wrapp">
                        <h3>نبذه عن الدكتور</h3>
                    </div>
                    <div class="white-card white-card-inner">
                        <div class="single_wrap" style="margin-top: 10px;">
                            <h4>معلومات عن الدكتور</h4>
                            <ul>
                                <p>{{doctor_detail.who_iam}} </p>
                            </ul>
                        </div>
                    </div>
                    <div class="single_wrap">
                        <h4>خدمات الدكتور :</h4>
                        <ul>
                            <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                            color: #808184;">   {{doctor_detail.specialist}} 
                            </p>
                        
                        </ul>
                        <br>
                    </div>
                    <div class="single_wrap">
                        <h4>صور العيادة :</h4>
                                <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                                <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                                <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                        
    
    
                    </div>
                </div>
    
        <!-- comments -->
        <div class="section-row">
            <div class="section-title">
                <h2 style="color: brown;">التعليقات (  )</h2>
            </div>
    
            <div class="post-comments" >
    
                <!-- comment -->
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="img/avatar.png" alt="">
                    </div>
                    <div class="media-body " >
                        <div class="media-heading">
                            <h4>اسم الكاتب</h4>
                            <span class="time">تم التعليق في </span>
                        </div>
                        <p>الكومنتات</p>
                        <a href="#" class="reply">الردود ..</a>
    
                        <!-- comment -->
                        <div class="media">
                            <div class="media-left">
                                <img class="media-object" src="" alt="">
                            </div>
                            <div class="media-body">
                                <div class="media-heading">
                                    <h4>محمود عبد الرؤف صبره</h4>
                                    <span class="time">تم التعليق فى </span>
                                </div>
                                <p>شكرا جدا واتمنى ان تتصفح باقي المواضيع .....</p>
                            </div>
                        </div>
                        <!-- /comment -->
                    </div>
                </div>
                <!-- /comment -->
    
                <div class="media-heading">
                    <h4>لا يوجد تعليقات حتى الأن ..</h4>
                </div>
    
            </div>
        </div>
        <!-- /comments -->                    
        <div class="apply_job_form white-bg">
            <h4>إترك تعليقك</h4>
            <form method="POST" >
    
                <div class="row">
                    <div class="col-md-6">
                        <div class="input_field">
                            <input type="text"  placeholder=" الإسم">
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input_field">
                            <input type="text"  placeholder=" الإيميل">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input_field">
                            <textarea  cols="30" rows="10" placeholder="تعليقك .."></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">تعليق</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>معلومات عن الدكتور </h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>  انضم إلينا : <span style="color: blue;"></span></li>
                            <li> الكشف : <span style="color: blue;"> {{doctor_detail.price}} <span>جنية</span></span></li>
                            <li> رقم الهاتف  : <span style="color: blue;">{{doctor_detail.number_phone}}</span></li>
                            <li>عدد ساعات العمل : <span style="color: blue;"> {{doctor_detail.working_hours}} <span>ساعات</span></span></li>
                        </ul>
                        
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>شارك الصفحه :</span>
                    <ul>
                        <li><a href="{{doctor_detail.facebook}}"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href=""> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href=""> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href=""> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                            var uluru = {lat: -25.363, lng: 131.044};
                            var grayStyles = [
                                {
                                featureType: "all",
                                stylers: [
                                    { saturation: -90 },
                                    { lightness: 50 }
                                ]
                                },
                                {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                            ];
                            var map = new google.maps.Map(document.getElementById('map'), {
                                center: {lat: -31.197, lng: 150.744},
                                zoom: 9,
                                styles: grayStyles,
                                scrollwheel:  false
                            });
                            }
                            
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        
                        </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock body %}

accounts/templates/user/doctors_list.html
{% extends "base.html" %}
{% load static %}
 {% block body %}
  

<div dir="rtl">
    <!-- Search -->
    {% include "user/search.html" %}
    <!-- end Search -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">
            
            <div class="job_lists">
               
                
                
                <div class="row">
                    {% for doctor in doctors  %}
                    <div class="col-lg-10 col-md-10" style="height: 16rem;" >
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                {% if doctor.image  %}
                                <div >
                            
                                <img  src="{{doctor.image.url}}" alt="" width="100" height="100">
                                         
                                </div>
                                {% else %}
                                <div >
                            
                                    <img  src="{% static 'img/profile.jpg' %}" alt="" width="100" height="100">
                                             
                                    </div>
                                {% endif %}
                                    
                             
                                <div class="jobs_conetent">
                                    <a href="{% url 'accounts:doctor-detail' doctor.slug %}" ><h5>{{doctor.name}}</h5></a> 
                                    <h6 style="color: green;">{{doctor.subtitle}}</h6>
                                    
                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;">{{doctor.specialist}}</span> متخصص في <span style="color: blue;">{{doctor.subtitle}}</span></p>
                                            <p style="color: blue;"> <i class="fa fa-map-marker" ></i>address : {{doctor.address}}</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;">{{doctor.price}}</span> جنية</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">{{doctor.waiting_time}}</span> دقيقة</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{doctor.working_hours}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> {{doctor.number_phone}} </span>  </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="">حجز كشف</a>
                                </div>
                     
                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        </div>
                                    <div class="rating" >
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>

                    {% endfor %}
                </div>
           
            </div> 
          
        </div>
    
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="img/candiateds/2.png" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- featured_candidates_area_end  -->


{% endblock body %}

accounts/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<div dir="rtl">
    <div class="container">
        <div class="signup">
            <div class="col-md-9" >
                <form method="POST" enctype="multipart/form-data" >
                    {% csrf_token %}

                    <h4 class="auth-header">تسجيل الدخول</h4>
                    <div class="form-group">
                        {{ form.username|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form.password|as_crispy_field }}
                    </div>
                    <div class="buttons-w">
                        <button type="submit" class="btn btn-success ml-5">تسجيل دخول</button>
                        <button type="submit" class="btn btn-info  ml-5"><a href="">Github</a></button>
                        <button type="submit" class="btn btn-primary  ml-5"><a href="">Facebook</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/user/search.html
<div class="catagory_area ">
<div class="container " style="margin-top: 10rem">
            <div class=" single_text">
                <h2>احجز مع
                    أفضل دكتور في مصر</h3>
                <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                <br>
            </div>
            <form  method="GET" action="">
            <div class="row cat_search" >

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <input type="text" placeholder="إسم الدكتور" >
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="" >الموقع</option>
                            <option value="المنصوره">المنصوره</option>
                            <option value="الدقي">الدقي</option>
                            <option value="4">Sylet</option>
                        </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option value="">التخصص</option>
                            <option value="جلدية">جلدية</option>
                            <option value="اسنان">اسنان</option>
                            <option value="نفسي">نفسي</option>
                            <option value="اطفال">اطفال حديثي الولادة</option>
                            <option value="مخ">مخ واعصاب</option>
                            <option value="عظام">عظام</option>
                            <option value="نساء">نساء وتوليد</option>
                            <option value="انف">انف واذن وحنجرة</option>
                            <option value="قلب">قلب واوعية دموية</option>
                            <option value="امراض">امراض دم</option>
                            <option value="اورام">اورام</option>
                            <option value="باطنه">باطنه</option>
                            <option value="تخسيس">تخسيس وتغذية</option>
                            <option value="جاطفال">جراحة اطفال</option>
                            <option value="جاورام">جراحة اورام</option>
                            <option value="جاوعيه">جراحة اوعية دموية</option>
                            <option value="جتجميل">جراحة تجميل</option>
                            <option value="سمنه">جراحه سمنة ومناظير </option>
                            </select>
                    </div>
                </div>

                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class="boxed-btn3" value="ابحث هنا">
                    </div>
                </div>

            </div>
            </form> 
        </div>
    </div>
    <!-- endsearch -->

accounts/templates/user/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div dir="rtl">
    <div class="container">
        <div class="signup">
    
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                <h4 class="auth-header">أنشاء حساب جديد</h4>
                 {% csrf_token %}
                 {{ form|crispy}}
                <div class="buttons-w"><button type="submit" class="btn btn-success">التسجيل</button></div>
    
            </form>
        </div>
        </div>
    </div>
    </div>
{% endblock body %}

accounts/templates/user/update_user.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

<div dir="rtl">


    <div class="container">
        <div class="signup">
    
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="auth-header">تحديث معلوماتك الشخصية</h4>
                    <div class="form-group">
                       
                        {{ user_form.email|as_crispy_field }}

    
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                       
                        {{ user_form.first_name|as_crispy_field }}

                        </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                        
                        {{ user_form.last_name|as_crispy_field }}

                        </div>
                    </div>
                    </div>
 
                <div class="buttons-w"><button type="submit" class="btn btn-success">تعديل</button></div>
                
            </form>
        </div>
        </div>
    </div>
    </div>
    
 

{% endblock body %}